### ISSUE TITLE
msb function can be improved

### ISSUE THREAD

**Issue by theoden8** [sinandredemption/M42#2]
Hey, thanks for some really good magics! Found through chessprogramming.com, using for my engine.

gprof shows that `msb` function is quite slow. Replacing its code with [`std::bit_width`](https://en.cppreference.com/w/cpp/header/bit) from `<bit>` has boosted performance.

The caveat is that this is c++20. Says [here](https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html) that this is what it uses under the hood.

Best,

K

**Comment by sinandredemption** [comment]
Hello @theoden8 

Thank you for informing me about this.

We can request the compiler to use hardware intrinsics to improve performance by using __builtin_clz on GCC and BitScanFoward() on MSVC. std::bit_width can be used just like you mentioned in case the compiler supports C++20. Using Macros, the code will be able to automatically detect all of these features at compile time, ensuring portability.

Best,
Fahad

**Comment by theoden8** [comment]
Hey, thanks for getting back

Indeed. The only thing that is concerning is that std::bit_width is not an ideal replacement - just plugging it in doesn't completely work (it occasionally returns an incorrect attack map). I don't understand it 100% but are you returning something different at msb(0)?

Best,
K

**Comment by sinandredemption** [comment]
Hello again.

The msb(0) function returns 0. However, the library should not _in theory_ depend on this, since msb() function never expects 0 as an argument (again, in theory).

If msb(0) is called, I am certain that this can be fixed. If it is convenient to you, please do share your std::bit_width experiments via a new branch so that I will be able to formally investigate into this.

Best,
Fahad

**Comment by theoden8** [comment]
Hey,

So, here's some code that doesn't work: https://github.com/sinandredemption/M42/pull/3.

If you run `make` it should make three executables: three of them benchmark perft of a [search explosion FEN](https://www.chessprogramming.org/Search_Explosion) as it involves a lot of file/rank xray finding. test_m42 may not give any  results.

The `m42_proxy.h` shows the difference between the two ways. Hope this is helpful.

Best,

Kirill

**Comment by sinandredemption** [comment]
Hello,

Thank you for this.

On a quick note before I clone your branch, would you please try replacing the line 123 in m42v2.h as mentioned in [this comment](https://github.com/sinandredemption/M42/pull/3/commits/dccaf873ec94d0646a9805ac60ac032482725ee4#r663388295) and inform me about the result. If I'm not mistaken, this should solve the discrepancy. However this is from the top of my head so I'm not sure.

Best,
Fahad

**Comment by theoden8** [comment]
I think it's working now. The rest is a bit of profiling.
